from __future__ import annotations

_PRIORITY_MAP = {
    "high": "High",
    "medium": "Medium",
    "low": "Low",
    "critical": "Critical",
}

_STATUS_MAP = {
    "ready": "Ready",
    "needswork": "NeedsWork",
    "notready": "NotReady",
}


def _map_step(step: dict) -> dict:
    return {
        "action": step.get("action") or "",
        "expected": step.get("expected") or "",
        "testData": step.get("test_data") or "",
        "comments": step.get("comments") or "",
    }


def _map_priority(priority: str | None) -> str:
    if not priority:
        return "Medium"
    return _PRIORITY_MAP.get(priority.lower(), "Medium")


def _map_status(status: str | None) -> str:
    if not status:
        return "NotReady"
    return _STATUS_MAP.get(status.lower().replace(" ", ""), "NotReady")


def build_draft_payload(
    improved: dict,
    source_id: str,
    project_id: str,
    section_id: str,
    source_attributes: dict | None = None,
    manual_notes: list[str] | None = None,
) -> dict:
    """Convert ImprovedTestCase dict into TestIT create-workitem payload."""
    status = improved.get("status")
    needs_review = _map_status(status) != "Ready"

    original_tags: list[str] = list(improved.get("tags") or [])
    draft_tags = [t for t in original_tags if t not in {"ai-generated", "needs-review"}]
    draft_tags = ["ai-generated"] + (["needs-review"] if needs_review else []) + draft_tags

    title = (improved.get("title") or "Untitled").removeprefix("[AI DRAFT] ")

    description = improved.get("description") or ""
    if needs_review:
        notes_block = ""
        if manual_notes:
            items = "\n".join(f"- {n}" for n in manual_notes)
            notes_block = f"\n\n**Требует доработки вручную:**\n{items}"
        footer = (
            f"\n\n---\n"
            f"🤖 Generated by qa-ai-tool  \n"
            f"Source work item: #{source_id}  \n"
            f"Needs QA review before replacing original"
            f"{notes_block}"
        )
        description = description + footer

    payload: dict = {
        "entityTypeName": "TestCases",
        "name": title,
        "description": description,
        "projectId": project_id,
        "sectionId": section_id,
        "state": _map_status(status),
        "priority": _map_priority(improved.get("priority")),
        "tags": [{"name": t} for t in draft_tags],
        "duration": int(improved.get("duration") or 60000),
        "steps": [_map_step(s) for s in (improved.get("steps") or [])],
        "preconditionSteps": [_map_step(s) for s in (improved.get("preconditions") or [])],
        "postconditionSteps": [_map_step(s) for s in (improved.get("postconditions") or [])],
        "attributes": source_attributes or {},
    }

    return payload
