from __future__ import annotations

_PRIORITY_MAP = {
    "high": "High",
    "medium": "Medium",
    "low": "Low",
    "critical": "Critical",
}


def _map_step(step: dict) -> dict:
    return {
        "action": step.get("action") or "",
        "expected": step.get("expected") or "",
        "testData": step.get("test_data") or "",
        "comments": step.get("comments") or "",
    }


def _map_priority(priority: str | None) -> str:
    if not priority:
        return "Medium"
    return _PRIORITY_MAP.get(priority.lower(), "Medium")


def build_draft_payload(
    improved: dict,
    source_id: str,
    project_id: str,
    section_id: str,
    source_attributes: dict | None = None,
) -> dict:
    """Convert ImprovedTestCase dict into TestIT create-workitem payload."""
    original_tags: list[str] = list(improved.get("tags") or [])
    draft_tags = [
        "ai-generated",
        "needs-review",
        f"source-{source_id}",
    ] + [t for t in original_tags if t not in {"ai-generated", "needs-review"}]

    title = improved.get("title") or "Untitled"
    draft_name = f"[AI DRAFT] {title}"

    description = improved.get("description") or ""
    footer = (
        f"\n\n---\n"
        f"🤖 Generated by qa-ai-tool  \n"
        f"Source work item: #{source_id}  \n"
        f"Needs QA review before replacing original"
    )
    draft_description = description + footer

    payload: dict = {
        "entityTypeName": "TestCases",
        "name": draft_name,
        "description": draft_description,
        "projectId": project_id,
        "sectionId": section_id,
        "state": "NotReady",
        "priority": _map_priority(improved.get("priority")),
        "tags": [{"name": t} for t in draft_tags],
        "duration": int(improved.get("duration") or 60000),
        "steps": [_map_step(s) for s in (improved.get("steps") or [])],
        "preconditionSteps": [_map_step(s) for s in (improved.get("preconditions") or [])],
        "postconditionSteps": [_map_step(s) for s in (improved.get("postconditions") or [])],
        "attributes": source_attributes or {},
    }

    return payload
