# backend/tests/test_testit_update_mapper.py
import pytest
from app.tms.testit.update_mapper import build_update_payload, _strip_service_footer


def test_strip_service_footer_removes_footer():
    desc = "Good description\n\n---\n🤖 Generated by qa-ai-tool\nSource work item: #6110"
    assert _strip_service_footer(desc) == "Good description"


def test_strip_service_footer_no_footer():
    desc = "Plain description"
    assert _strip_service_footer(desc) == "Plain description"


def test_strip_service_footer_empty():
    assert _strip_service_footer("") == ""
    assert _strip_service_footer(None) == ""


def _make_raw(extra_tags=None):
    tags = [{"name": "regression"}, {"name": "source-6110"}, {"name": "needs-review"}]
    if extra_tags:
        tags += [{"name": t} for t in extra_tags]
    return {
        "id": "abc-123",
        "globalId": 42,
        "projectId": "proj-uuid",
        "sectionId": "sec-uuid",
        "entityTypeName": "TestCases",
        "name": "Old title",
        "description": "Old desc",
        "state": "NotReady",
        "priority": "Medium",
        "duration": 60000,
        "steps": [],
        "preconditionSteps": [],
        "postconditionSteps": [],
        "tags": tags,
        "attributes": {},
    }


def _make_improved():
    return {
        "title": "[AI DRAFT] New title",
        "description": "New description\n\n---\n🤖 Generated by qa-ai-tool\nSource work item: #6110\nNeeds QA review",
        "priority": "high",
        "status": "NeedsWork",
        "duration": 90000,
        "steps": [{"action": "Do thing", "expected": "Thing done", "test_data": None, "comments": None}],
        "preconditions": [],
        "postconditions": [],
        "tags": ["ai-generated", "regression"],
    }


def test_build_update_payload_preserves_metadata():
    raw = _make_raw()
    improved = _make_improved()
    payload = build_update_payload(raw, improved, "6110")

    assert payload["id"] == "abc-123"
    assert payload["projectId"] == "proj-uuid"
    assert payload["sectionId"] == "sec-uuid"
    assert payload["entityTypeName"] == "TestCases"


def test_build_update_payload_strips_ai_draft_prefix():
    raw = _make_raw()
    improved = _make_improved()
    payload = build_update_payload(raw, improved, "6110")
    assert payload["name"] == "New title"


def test_build_update_payload_strips_service_footer():
    raw = _make_raw()
    improved = _make_improved()
    payload = build_update_payload(raw, improved, "6110")
    assert "🤖" not in payload["description"]
    assert payload["description"] == "New description"


def test_build_update_payload_tag_cleanup():
    raw = _make_raw(extra_tags=["smoke"])
    improved = _make_improved()
    payload = build_update_payload(raw, improved, "6110")

    tag_names = {t["name"] for t in payload["tags"]}
    assert "source-6110" not in tag_names
    assert "needs-review" not in tag_names
    assert "ai-generated" in tag_names
    assert "regression" in tag_names
    assert "smoke" in tag_names


def test_build_update_payload_maps_steps():
    raw = _make_raw()
    improved = _make_improved()
    payload = build_update_payload(raw, improved, "6110")

    assert len(payload["steps"]) == 1
    assert payload["steps"][0]["action"] == "Do thing"
    assert payload["steps"][0]["expected"] == "Thing done"


def test_build_update_payload_maps_priority():
    raw = _make_raw()
    improved = _make_improved()
    payload = build_update_payload(raw, improved, "6110")
    assert payload["priority"] == "High"


def test_build_update_payload_passes_through_unrecognized_priority():
    # A project-specific priority value ("Blocker", "P1", ...) that the LLM
    # left untouched shouldn't be silently downgraded to Medium.
    raw = _make_raw()
    improved = _make_improved()
    improved["priority"] = "Blocker"
    payload = build_update_payload(raw, improved, "6110")
    assert payload["priority"] == "Blocker"


def test_build_update_payload_defaults_missing_priority_to_medium():
    raw = _make_raw()
    improved = _make_improved()
    improved["priority"] = None
    payload = build_update_payload(raw, improved, "6110")
    assert payload["priority"] == "Medium"


def test_build_update_payload_keeps_original_priority_verbatim_when_unchanged():
    # LLM echoed the same priority back untouched (no priority issue was
    # fixed) — pass the original TestIT value through as-is, don't normalize
    # it even if our own map would've capitalized it differently.
    raw = _make_raw()
    raw["priority"] = "highest"
    improved = _make_improved()
    improved["priority"] = "highest"
    payload = build_update_payload(raw, improved, "6110")
    assert payload["priority"] == "highest"


def test_build_update_payload_maps_state():
    raw = _make_raw()
    improved = _make_improved()
    payload = build_update_payload(raw, improved, "6110")
    assert payload["state"] == "NeedsWork"
